return {
  command = "TerminalPopup",
  keymap = nil,
  width = "90%",
  height = "85%",
  socket = "nvim-popup",
  session_prefix = "nvim",
  tmux_command = "tmux",
  title = "terminal: {name}  {close} close",
  name = nil,
  theme = "auto",
  popup_style = nil,
  border_style = nil,
  scope = "project",
  start_command = nil,
  close_keys = { "C-g", "F12" },
  outer_close_keys = {},
  prefix = nil,
  prefix_close_keys = { "d", "q" },
  status = "off",
  mouse = nil,
  default_terminal = nil,
  terminal_overrides = nil,
  root_markers = {
    ".git",
    "Cargo.toml",
    "go.mod",
    "package.json",
    "pyproject.toml",
  },
}
